backend:
  url: www.dev.backend
  user: devUser
  password: '{cipher}AgAV/+L1d7UgebFl2ubaDU1sMzfNU5bLBTor6M/61ww7f0AZO5otTSImNw2///0GMaD55oO8neVMH4XlW9czd0GWgZwETIDjJZL/wbT68CmTlcLnDKgUWMt2IqxzGk0W+sdF1PhTjp0FRW7W1oHIxAY6dkkySk5Ry+pt5L4lKTeevnrTFPoL3jsgletKnm69O+j0rqyK8wzeSkUltMnsGj8g3dNVF1p8D59qnIIaUvDJezq9fymQwieO18ecMqlEFJjoXwlKGmgF80w/CrlSZazKmiWy6/TMflpC0AyZ7ybpGOuSJrRgkIgfyBfhfQVHCtn3HJbDZkrUD1CExchJfiBv81FCxqhg6diUAEwM9/ZkmZ308vOCUJ91znGA0eLGg2GaLf15U3dVq6R4AJI2RWLa/PoKnqI1vgWECRuoJMiU/W8P62Gi+cq76llDUfshLMClfpBx327jdwqmfhd9uhcaUMiheyctkMHebaOZ95vF6NJZEgMkVSNngosuHLrIVK5zlN/elyK3Oo7Vy6+OUdjanq+QwDDtDOTqEMVblWXm8WBu3Qa6soSxIlTJxYSl0k6pgoeBpE9bPipkEIvIPXdksoGFpB2NRJvUIRgAsq8O1G9LOpC0N14jVXbnQoDPKU6EkBydzEOnyRDf+WLzEwBA0jYiOKHfLGK9ikt7M33QgmxUDaaxQDkJjvv3mlA204tC0fCHTd5Ef5wqKDg9wdia'

frontend:
  url: www.dev.app